name = "SuiteSplinesRegistry"
uuid = "df7358ec-30c0-41d2-becf-685aef48513c"
repo = "https://github.com/SuiteSplines/SuiteSplinesRegistry.git"
description = "SuiteSplines local registry"

[packages]
2552f6ce-f0d6-4ba3-bf39-bb338613ee69 = { name = "UnivariateSplines", path = "U/UnivariateSplines" }
2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc = { name = "SortedSequences", path = "S/SortedSequences" }
3119edd0-0685-4064-9500-10252e0e5727 = { name = "NURBS", path = "N/NURBS" }
3811570c-b24d-4931-9f1c-72ee5a79a1d1 = { name = "IgaFormation", path = "I/IgaFormation" }
3e3b8edd-9419-4511-a852-83e823fd4317 = { name = "ImmersedSplines", path = "I/ImmersedSplines" }
5766f8de-d509-470a-8420-f491b24ab91b = { name = "KroneckerProducts", path = "K/KroneckerProducts" }
6606482d-3ef5-47b1-bd38-b02eeb053191 = { name = "SuiteSplinesExampleDep", path = "S/SuiteSplinesExampleDep" }
7dac2afd-1bf6-47b8-bc94-9dcdcd19d527 = { name = "AbstractMappings", path = "A/AbstractMappings" }
89f2e70f-f704-4f07-9b81-69bdc44074b1 = { name = "TensorProductBsplines", path = "T/TensorProductBsplines" }
95516d86-82af-438a-ae84-b941c80ea631 = { name = "ImplicitGeometries", path = "I/ImplicitGeometries" }
9c103fa8-ae55-49f5-92db-ab77803cf2c4 = { name = "IgaBase", path = "I/IgaBase" }
b2e007fe-26bf-4abf-a2e9-4b2a1ab78b25 = { name = "LocalRegistrator", path = "L/LocalRegistrator" }
c1439797-f1c6-466c-87a0-2eb89882a10c = { name = "SuiteSplines", path = "S/SuiteSplines" }
cc3e65be-d4cb-4562-9ae2-5262579a9956 = { name = "SpecialSpaces", path = "S/SpecialSpaces" }
ddfd9c64-15e7-45fc-8e16-950f3835cae5 = { name = "CartesianProducts", path = "C/CartesianProducts" }
e2515d83-272f-46f3-a47f-6d1ac1d67685 = { name = "BezierBernsteinMethods", path = "B/BezierBernsteinMethods" }
f85cb439-bc22-49c8-a213-82e476719812 = { name = "SuiteSplinesExamplePkg", path = "S/SuiteSplinesExamplePkg" }
