name = "SuiteSplinesRegistry"
uuid = "df7358ec-30c0-41d2-becf-685aef48513c"
repo = "https://github.com/SuiteSplines/SuiteSplinesRegistry.git"
description = "SuiteSplines local registry"

[packages]
2f2e3dc8-c2cf-4b7f-b456-36845a1cbdbc = { name = "SortedSequences", path = "S/SortedSequences" }
6606482d-3ef5-47b1-bd38-b02eeb053191 = { name = "SuiteSplinesExampleDep", path = "S/SuiteSplinesExampleDep" }
b2e007fe-26bf-4abf-a2e9-4b2a1ab78b25 = { name = "LocalRegistrator", path = "L/LocalRegistrator" }
f85cb439-bc22-49c8-a213-82e476719812 = { name = "SuiteSplinesExamplePkg", path = "S/SuiteSplinesExamplePkg" }
